-- public.categories definition

-- Drop table

-- DROP TABLE public.categories;

CREATE TABLE public.categories (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	category varchar(255) NOT NULL,
	created_at timestamptz(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT categories_category_check CHECK (((category)::text = ANY ((ARRAY['SoloArtist'::character varying, 'FestivalMusic'::character varying, 'Opera'::character varying, 'ClassicalMusic'::character varying, 'JazzMusic'::character varying])::text[]))),
	CONSTRAINT categories_pkey PRIMARY KEY (id)
);


-- public.cities definition

-- Drop table

-- DROP TABLE public.cities;

CREATE TABLE public.cities (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"name" varchar(255) NOT NULL,
	created_at timestamptz(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT cities_name_check CHECK (((name)::text = ANY ((ARRAY['Jakarta'::character varying, 'Bali'::character varying, 'Bandung'::character varying, 'Surabaya'::character varying, 'Medan'::character varying])::text[]))),
	CONSTRAINT cities_pkey PRIMARY KEY (id)
);


-- public.users definition

-- Drop table

-- DROP TABLE public.users;

CREATE TABLE public.users (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	avatar varchar(255) NULL,
	created_at timestamptz(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
	deleted_at timestamptz(6) NULL,
	email varchar(100) NOT NULL,
	"password" varchar(100) NOT NULL,
	referral_code varchar(255) NULL,
	"role" varchar(255) NOT NULL,
	updated_at timestamptz(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
	username varchar(100) NOT NULL,
	CONSTRAINT users_pkey PRIMARY KEY (id),
	CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['User'::character varying, 'Organizer'::character varying])::text[])))
);


-- public.events definition

-- Drop table

-- DROP TABLE public.events;

CREATE TABLE public.events (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamptz(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"date" date NOT NULL,
	deleted_at timestamptz(6) NULL,
	description varchar(255) NOT NULL,
	end_time time(6) NOT NULL,
	event_name varchar(255) NOT NULL,
	image varchar(255) NULL,
	free_event bool NOT NULL,
	"location" varchar(255) NOT NULL,
	start_time time(6) NOT NULL,
	thumbnail varchar(255) NULL,
	updated_at timestamptz(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
	category_id int8 NOT NULL,
	city_id int8 NOT NULL,
	user_id int8 NOT NULL,
	CONSTRAINT events_pkey PRIMARY KEY (id),
	CONSTRAINT uk56605aq1n0eb6x365ghtn8sku UNIQUE (city_id),
	CONSTRAINT ukk46y4v0g1ddq68uiuj3t8ltup UNIQUE (category_id),
	CONSTRAINT fkat8p3s7yjcp57lny4udqvqncq FOREIGN KEY (user_id) REFERENCES public.users(id),
	CONSTRAINT fko6mla8j1p5bokt4dxrlmgwc28 FOREIGN KEY (category_id) REFERENCES public.categories(id),
	CONSTRAINT fkoqicyi54u66pj29af47da15xk FOREIGN KEY (city_id) REFERENCES public.cities(id)
);


-- public.points definition

-- Drop table

-- DROP TABLE public.points;

CREATE TABLE public.points (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamptz(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
	deleted_at timestamptz(6) NULL,
	point int8 NOT NULL,
	updated_at timestamptz(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
	user_id int8 NOT NULL,
	CONSTRAINT points_pkey PRIMARY KEY (id),
	CONSTRAINT fkr49p6spgfhomh11aksag7al0d FOREIGN KEY (user_id) REFERENCES public.users(id)
);


-- public.referrals definition

-- Drop table

-- DROP TABLE public.referrals;

CREATE TABLE public.referrals (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	claimed bool NOT NULL,
	created_at timestamptz(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
	deleted_at timestamptz(6) NULL,
	referrer_id int8 NOT NULL,
	updated_at timestamptz(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
	user_id int8 NOT NULL,
	CONSTRAINT referrals_pkey PRIMARY KEY (id),
	CONSTRAINT uketnherpemnkjd9rin40p50i8a UNIQUE (user_id),
	CONSTRAINT fkfwkm1id8x0tg6krip9kcpq18u FOREIGN KEY (user_id) REFERENCES public.users(id)
);


-- public.reviews definition

-- Drop table

-- DROP TABLE public.reviews;

CREATE TABLE public.reviews (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamptz(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ratings float8 NOT NULL,
	reviews varchar(255) NULL,
	event_id int8 NOT NULL,
	user_id int8 NOT NULL,
	CONSTRAINT reviews_pkey PRIMARY KEY (id),
	CONSTRAINT fkcgy7qjc1r99dp117y9en6lxye FOREIGN KEY (user_id) REFERENCES public.users(id),
	CONSTRAINT fkem6jjo18jyueiqhferf3dwfbx FOREIGN KEY (event_id) REFERENCES public.events(id)
);


-- public.tickets definition

-- Drop table

-- DROP TABLE public.tickets;

CREATE TABLE public.tickets (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	available_seat int4 NOT NULL,
	created_at timestamptz(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
	deleted_at timestamptz(6) NULL,
	price int8 NOT NULL,
	"type" varchar(255) NOT NULL,
	updated_at timestamptz(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
	event_id int8 NOT NULL,
	CONSTRAINT tickets_pkey PRIMARY KEY (id),
	CONSTRAINT fk3utafe14rupaypjocldjaj4ol FOREIGN KEY (event_id) REFERENCES public.events(id)
);


-- public.coupons definition

-- Drop table

-- DROP TABLE public.coupons;

CREATE TABLE public.coupons (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamptz(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
	discounts float8 NOT NULL,
	end_date date NOT NULL,
	is_referral_promo bool NOT NULL,
	limits int4 NOT NULL,
	start_date date NOT NULL,
	updated_at timestamptz(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
	event_id int8 NOT NULL,
	CONSTRAINT coupons_pkey PRIMARY KEY (id),
	CONSTRAINT fkd9nbpn6913voggfih5b5rltj FOREIGN KEY (event_id) REFERENCES public.events(id)
);


-- public.transactions definition

-- Drop table

-- DROP TABLE public.transactions;

CREATE TABLE public.transactions (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamptz(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
	original_price int8 NOT NULL,
	total_discount int8 NULL,
	total_price int8 NOT NULL,
	use_points int8 NULL,
	coupon_id int8 NULL,
	event_id int8 NOT NULL,
	user_id int8 NOT NULL,
	CONSTRAINT transactions_pkey PRIMARY KEY (id),
	CONSTRAINT uk69rxjyswr58be9watmxv0dp5y UNIQUE (event_id),
	CONSTRAINT ukgswewj70dupn0rxxpjy4gml4l UNIQUE (coupon_id),
	CONSTRAINT fkadbwpqfaxy7y5m85pxpx5yvru FOREIGN KEY (coupon_id) REFERENCES public.coupons(id),
	CONSTRAINT fke01y6qhe8lfkj74f0nac6mbmk FOREIGN KEY (event_id) REFERENCES public.events(id),
	CONSTRAINT fkqwv7rmvc8va8rep7piikrojds FOREIGN KEY (user_id) REFERENCES public.users(id)
);


-- public.order_item definition

-- Drop table

-- DROP TABLE public.order_item;

CREATE TABLE public.order_item (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamptz(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
	deleted_at timestamptz(6) NULL,
	ticket_qty int4 NOT NULL,
	updated_at timestamptz(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ticket_id int8 NOT NULL,
	transaction_id int8 NOT NULL,
	CONSTRAINT order_item_pkey PRIMARY KEY (id),
	CONSTRAINT fkg1vk0fb482sk8lv0kw6twmkfp FOREIGN KEY (transaction_id) REFERENCES public.transactions(id),
	CONSTRAINT fkhpmoejhoniqfe0xcjtmm9aq70 FOREIGN KEY (ticket_id) REFERENCES public.tickets(id)
);